# Generated by Django 5.2.4 on 2025-07-09 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crime",
            options={"verbose_name": "Violence Event"},
        ),
        migrations.RenameField(
            model_name="crime",
            old_name="feast_day",
            new_name="liturgical_occassion",
        ),
    ]
