# Generated by Django 5.2.4 on 2025-08-05 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Event", "verbose_name_plural": "Events"},
        ),
    ]
