# Generated by Django 5.2.4 on 2025-10-21 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("mapping_violence", "0002_alter_event_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crime",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="crime",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="crime",
            name="input_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Person who entered record.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Input by (user)",
            ),
        ),
        migrations.AlterField(
            model_name="crime",
            name="judge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mapping_violence.person",
            ),
        ),
        migrations.AlterField(
            model_name="crime",
            name="weapon",
            field=models.ForeignKey(
                blank=True,
                help_text="Input type of weapon if known according to taxonomy (firearm, edged weapon, blunt instrument, hands)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mapping_violence.weapon",
                verbose_name="Type of Weapon",
            ),
        ),
    ]
