# Generated by Django 5.2.4 on 2025-07-09 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0002_alter_crime_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crime",
            old_name="liturgical_occassion",
            new_name="liturgical_occasion",
        ),
    ]
