# Generated by Django 5.2.4 on 2025-10-21 16:13

import django.db.models.deletion
from django.db import migrations, models

import historical_dates.fields


class Migration(migrations.Migration):
    dependencies = [
        ("historical_dates", "0001_initial"),
        ("mapping_violence", "0003_crime_updated_by_alter_crime_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crime",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Input modern format of date. Example: October 23, 1615 should be converted to 1615-10-23",
                null=True,
                verbose_name="Date (Modern Format)",
            ),
        ),
        migrations.AlterField(
            model_name="crime",
            name="historical_date",
            field=historical_dates.fields.HistoricalDateField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="historical_dates.historicaldate",
            ),
        ),
    ]
