# Generated by Django 5.2.4 on 2025-07-17 15:41

import django.db.models.deletion
from django.db import migrations, models

import historical_dates.fields


class Migration(migrations.Migration):
    dependencies = [
        ("historical_dates", "0002_alter_historicaldate_edtf_date"),
        (
            "mapping_violence",
            "0003_rename_liturgical_occassion_crime_liturgical_occasion",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WeaponCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="crime",
            name="accord",
            field=models.BooleanField(
                default=False, verbose_name="Did the case end with a peace accord?"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="crime",
            name="accord_date",
            field=models.DateField(
                blank=True,
                help_text="If an accord was reached, what was the date?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="definition",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="weapon",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mapping_violence.weaponcategory",
            ),
        ),
        migrations.CreateModel(
            name="Witness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claims", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "date_of_testimony",
                    historical_dates.fields.HistoricalDateField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="historical_dates.historicaldate",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mapping_violence.person",
                    ),
                ),
            ],
        ),
    ]
