# Generated by Django 5.2.7 on 2025-11-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0005_alter_crime_input_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="repeat_offender",
            field=models.BooleanField(default=False),
        ),
    ]
