# Generated by Django 5.2.7 on 2026-02-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0006_person_repeat_offender"),
    ]

    operations = [
        migrations.AddField(
            model_name="crime",
            name="sentence_in_absentia",
            field=models.BooleanField(
                default=False,
                help_text="Was the sentence issued in absentia (in contumacia)? Check Y if the person was sentenced without being present.",
                verbose_name="In Contumacia (Y/N)",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="nationality_ethnicity",
            field=models.CharField(
                blank=True,
                help_text="Input nationality or ethnicity if recorded in the source, e.g. Ottoman, Jewish, Greek",
                max_length=255,
                null=True,
                verbose_name="Nationality/Ethnicity",
            ),
        ),
    ]
