# Generated by Django 5.2.7 on 2026-02-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0007_add_nationality_ethnicity_and_sentence_in_absentia"),
    ]

    operations = [
        migrations.AddField(
            model_name="crime",
            name="offense_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("homicide", "Homicide"),
                    ("premeditated_homicide", "Pre-meditated Homicide"),
                    ("insult", "Insult"),
                    ("sexual_offenses", "Sexual Offenses"),
                    ("abduction", "Abduction"),
                    ("assault", "Assault"),
                    ("other", "Other"),
                ],
                help_text="Select the top-level offense category",
                max_length=50,
                verbose_name="Offense Category",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="weapon_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("firearm", "Firearm"),
                    ("blade", "Blade"),
                    ("blunt_instrument", "Blunt Instrument"),
                    ("hands", "Hands"),
                    ("other", "Other"),
                ],
                help_text="Select the top-level weapon category",
                max_length=50,
                verbose_name="Weapon Category",
            ),
        ),
        migrations.AddField(
            model_name="weapon",
            name="weapon_subcategory",
            field=models.CharField(
                blank=True,
                help_text="Enter subcategory (e.g. pistol, arquebus, dagger, sword, club)",
                max_length=255,
                verbose_name="Weapon Subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mapping_violence.weaponcategory",
            ),
        ),
    ]
