# Generated by Django 5.2.7 on 2026-02-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0008_add_weapon_category_subcategory_offense_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crime",
            name="motive",
            field=models.TextField(
                blank=True,
                help_text="Input description of motive as given, if known: example: mortal hatred",
            ),
        ),
    ]
