# Generated by Django 5.2.7 on 2026-03-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0010_alter_crime_input_by_alter_crime_updated_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="given_name",
            field=models.CharField(
                blank=True,
                help_text="How the person is commonly referred to in sources. Used as the display name when present.",
                max_length=255,
                verbose_name="Given name (display name)",
            ),
        ),
    ]
