# Generated by Django 5.2.7 on 2026-03-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0011_person_given_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="honorific",
            field=models.CharField(
                blank=True,
                help_text="Input honorific or title, if known. Example: Ser, Madonna, Messer, Magnifico",
                max_length=255,
            ),
        ),
    ]
