# Generated by Django 5.2.7 on 2026-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0012_add_person_honorific"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["last_name", "first_name"], name="person_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["given_name"], name="person_given_name_idx"),
        ),
    ]
