# Generated by Django 5.2.7 on 2026-04-22 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0013_add_person_name_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["name"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="weapon",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="weaponcategory",
            options={"ordering": ["name"]},
        ),
    ]
