# Generated by Django 5.2.7 on 2026-05-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0015_rename_hands_to_no_weapon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crime",
            name="weapon",
            field=models.ForeignKey(
                blank=True,
                help_text="Input type of weapon if known according to taxonomy (firearm, edged weapon, blunt instrument, no weapon)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mapping_violence.weapon",
                verbose_name="Type of Weapon",
            ),
        ),
        migrations.AlterField(
            model_name="weapon",
            name="weapon_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("firearm", "Firearm"),
                    ("blade", "Blade"),
                    ("blunt_instrument", "Blunt Instrument"),
                    ("no_weapon", "No weapon"),
                    ("other", "Other"),
                ],
                help_text="Select the top-level weapon category",
                max_length=50,
                verbose_name="Weapon Category",
            ),
        ),
    ]
