# Generated by Django 5.2.7 on 2026-05-05 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0016_update_weapon_category_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="crime",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Editor responsible for this record",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_crimes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AddField(
            model_name="crime",
            name="status",
            field=models.CharField(
                choices=[
                    ("triage", "Triage"),
                    ("assigned", "Assigned"),
                    ("needs_review", "Needs Review"),
                    ("done", "Done"),
                ],
                db_index=True,
                default="triage",
                help_text="Workflow status of this record",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("triage", "Triage"),
                            ("assigned", "Assigned"),
                            ("needs_review", "Needs Review"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("triage", "Triage"),
                            ("assigned", "Assigned"),
                            ("needs_review", "Needs Review"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "crime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="mapping_violence.crime",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
