# Generated by Django 5.2.7 on 2026-07-09 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "mapping_violence",
            "0020_convert_weapon_fk_to_m2m_and_remove_weapon_category",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=500)),
                ("import_profile", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("imported", "Imported"),
                            ("needs_review", "Needs Review"),
                            ("failed", "Failed"),
                        ],
                        default="staged",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_batches",
                        to="mapping_violence.sourcedataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "original_filename"],
            },
        ),
        migrations.AddField(
            model_name="crime",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crimes",
                to="mapping_violence.importbatch",
            ),
        ),
        migrations.CreateModel(
            name="ExternalPersonIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("raw_name", models.CharField(blank=True, max_length=500)),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("created", "Created"),
                            ("ambiguous_name_reused", "Ambiguous name reused"),
                            ("unresolved", "Unresolved"),
                        ],
                        default="unresolved",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_identifiers",
                        to="mapping_violence.person",
                    ),
                ),
                (
                    "source_dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person_identifiers",
                        to="mapping_violence.sourcedataset",
                    ),
                ),
            ],
            options={
                "ordering": ["source_dataset__name", "external_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_dataset", "external_id"),
                        name="unique_external_person_identifier",
                    )
                ],
            },
        ),
    ]
