# Generated by Django 5.2.7 on 2026-08-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mapping_violence", "0021_add_import_provenance_and_external_person_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="content_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rows_created",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rows_errored",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rows_skipped",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rows_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="rows_updated",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="crime",
            name="number",
            field=models.CharField(
                blank=True,
                help_text="Archival or source case number, e.g. 001. This value is optional and is not required to be unique.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="importbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("staged", "Staged"),
                    ("imported", "Imported"),
                    ("needs_review", "Needs Review"),
                    ("failed", "Failed"),
                    ("rolled_back", "Rolled Back"),
                ],
                default="staged",
                max_length=20,
            ),
        ),
    ]
