# Generated by Django 5.2.4 on 2025-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_date",
                    models.CharField(
                        help_text="Human-readable date (e.g. 'circa 1850', 'early 19th century').",
                        max_length=255,
                    ),
                ),
                (
                    "edtf_date",
                    models.CharField(
                        blank=True,
                        help_text='EDTF expression (e.g. "1850-03~" or "1800/1850"). See <a href="https://www.loc.gov/standards/datetime/" target="_blank" rel="noopener">EDTF documentation</a>.',
                        max_length=255,
                        verbose_name="EDTF date",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("approximate", "Approximate"),
                            ("uncertain", "Uncertain"),
                        ],
                        default="exact",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
