# Generated by Django 5.2.4 on 2025-07-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("historical_dates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaldate",
            name="edtf_date",
            field=models.CharField(
                blank=True,
                help_text='EDTF expression (e.g. "1850-03~" or "1800/1850"). See <a href="https://www.loc.gov/standards/datetime/" target="_blank" rel="noopener">EDTF documentation</a>.',
                max_length=255,
                verbose_name="EDTF date",
            ),
        ),
    ]
