# Generated by Django 5.2.4 on 2025-08-05 18:29

import django.db.models.deletion
import wagtail.fields
import wagtail.models.preview
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Internal title for this content block",
                        max_length=255,
                    ),
                ),
                (
                    "lede",
                    models.TextField(
                        help_text="Short introductory text that appears prominently",
                        max_length=500,
                    ),
                ),
                (
                    "main_content",
                    wagtail.fields.RichTextField(
                        help_text="Main body content for the left column of the home page"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only one home page content block should be active at a time",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Page Content",
                "verbose_name_plural": "Home Page Content",
                "ordering": ["-updated_at"],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProjectPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        help_text="Their role on the project (e.g., Principal Investigator, Research Associate) - optional",
                        max_length=255,
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        help_text="Associated institution", max_length=255
                    ),
                ),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("project_team", "Project Team"),
                            ("advisory_board", "Advisory Board"),
                        ],
                        default="project_team",
                        help_text="Whether this person is part of the Project Team or Advisory Board",
                        max_length=20,
                    ),
                ),
                (
                    "bio",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Brief biographical information (optional)",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this person appears within their group (lower numbers first)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this person should be displayed on the site",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile_photo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Profile photo for the team member",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_people",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Person",
                "verbose_name_plural": "Project People",
                "ordering": ["team_type", "display_order", "name"],
            },
            bases=(wagtail.models.preview.PreviewableMixin, models.Model),
        ),
    ]
