# Generated by Django 5.2.4 on 2025-08-14 16:10

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(
                        help_text="Main content for the About page"
                    ),
                ),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HistoricalContextPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(
                        help_text="Main content for the Historical Context page"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historical Context Page",
                "verbose_name_plural": "Historical Context Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
