# Generated by Django 5.2.4 on 2025-08-18 14:28

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_aboutpage_historicalcontextpage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.RichTextField(help_text="Main content for the page"),
                ),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.RemoveField(
            model_name="historicalcontextpage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="AboutPage",
        ),
        migrations.DeleteModel(
            name="HistoricalContextPage",
        ),
    ]
