# Generated by Django 5.2.4 on 2025-08-18 14:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_generalpage_remove_historicalcontextpage_page_ptr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("paragraph", 0), ("image_gallery", 6)],
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"help_text": "Rich text content"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional title for the gallery",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    3: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Optional caption for the image",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 2), ("caption", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.ListBlock",
                        (4,),
                        {"help_text": "Add images to the gallery"},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 1), ("images", 5)]],
                        {},
                    ),
                },
                help_text="Main content for the page",
            ),
        ),
    ]
