# Generated by Django 5.2.7 on 2026-04-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_blogindexpage_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalpage",
            name="author",
            field=models.CharField(
                blank=True,
                help_text="Author of this page (e.g., for guide essays)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="generalpage",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Short summary or excerpt displayed in table-of-contents listings",
            ),
        ),
    ]
