# Generated by Django 5.2.4 on 2025-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("current_name", models.CharField(max_length=255)),
                (
                    "admin_unit",
                    models.CharField(
                        max_length=255, verbose_name="Administrative unit"
                    ),
                ),
                (
                    "parish",
                    models.CharField(
                        blank=True, help_text="Input Parish, if known", max_length=255
                    ),
                ),
                (
                    "parish_religious_order",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Religious order",
                    ),
                ),
                (
                    "sestiere",
                    models.CharField(
                        blank=True,
                        help_text="If Venetian crime, input neighborhood",
                        max_length=255,
                    ),
                ),
                (
                    "description_of_location",
                    models.TextField(
                        blank=True,
                        help_text="Input description of location if given. Example: in front of the Madonna di Miracoli, on the bridge of sighs",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        help_text="Input city (or village), if known. Example: Venice, Lake Garda",
                        max_length=255,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("landmark", models.CharField(blank=True, max_length=255, null=True)),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Non-public notes on the location.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "category_of_space",
                    models.CharField(
                        blank=True,
                        help_text="Input category of space, if applicable (sacred, public, domestic)",
                        max_length=255,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="This will be auto-generated if left empty.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="This will be auto-generated if left empty.",
                        max_digits=9,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
