# Generated by Django 5.2.4 on 2025-07-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="admin_unit",
            field=models.CharField(
                default="", max_length=255, verbose_name="Administrative unit"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="current_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="location",
            name="parish_religious_order",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Religious order"
            ),
        ),
    ]
