# Generated by Django 5.2.4 on 2025-10-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "parish",
                    models.CharField(
                        blank=True,
                        help_text="Administrative parish or region",
                        max_length=255,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="General city latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="General city longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about the city", null=True
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.RemoveField(
            model_name="location",
            name="parish",
        ),
        migrations.AlterField(
            model_name="location",
            name="admin_unit",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Administrative unit"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="category_of_space",
            field=models.CharField(
                blank=True,
                help_text="Category of space: sacred, public, domestic, etc.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="current_name",
            field=models.CharField(
                blank=True, help_text="Current name if different", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="description_of_location",
            field=models.TextField(
                blank=True,
                help_text="Specific description: in front of the Madonna di Miracoli, on the bridge of sighs",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Specific location latitude (falls back to city coordinates if empty)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Specific location longitude (falls back to city coordinates if empty)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                help_text="Name of the specific location", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Non-public notes on this specific location",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="sestiere",
            field=models.CharField(
                blank=True,
                help_text="If Venetian location, input neighborhood",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="city",
            field=models.ForeignKey(
                help_text="The city this location is in",
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.city",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("category_of_space__isnull", False),
                    ("description_of_location__isnull", False),
                    _connector="OR",
                ),
                fields=("city", "category_of_space", "description_of_location"),
                name="unique_location_in_city",
            ),
        ),
    ]
