# Generated by Django 5.2.4 on 2025-10-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_city_remove_location_parish_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_location_in_city",
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("city", "category_of_space", "description_of_location"),
                name="unique_location_in_city",
            ),
        ),
    ]
