# Generated by Django 5.2.7 on 2026-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_remove_location_unique_location_in_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="urban_rural",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urban", "Urban"),
                    ("rural", "Rural"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Classify this location as urban (citta) or rural (contado)",
                max_length=10,
                verbose_name="Urban/Rural",
            ),
        ),
    ]
