# Generated by Django 5.2.7 on 2026-03-20 15:51

from django.db import migrations


def classify_existing_locations(apps, schema_editor):
    """Auto-classify existing locations based on name containing contado/citta."""
    Location = apps.get_model("locations", "Location")
    for location in Location.objects.all():
        combined = f"{location.name} {location.city.name}".lower()
        if "contado" in combined:
            location.urban_rural = "rural"
            location.save(update_fields=["urban_rural"])
        elif "citta" in combined or "città" in combined:
            location.urban_rural = "urban"
            location.save(update_fields=["urban_rural"])


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_location_urban_rural"),
    ]

    operations = [
        migrations.RunPython(
            classify_existing_locations,
            migrations.RunPython.noop,
        ),
    ]
