# Generated by Django 5.2.7 on 2026-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_classify_urban_rural"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"], "verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_location_in_city",
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("category_of_space", ""), _negated=True),
                    models.Q(("description_of_location", ""), _negated=True),
                ),
                fields=("city", "category_of_space", "description_of_location"),
                name="unique_location_in_city",
            ),
        ),
    ]
