# Generated by Django 5.2.7 on 2026-04-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0006_alter_city_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Modern country name (e.g., Italy, United Kingdom, Germany)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Historical or modern region (e.g., Veneto, Lombardy, Terraferma)",
                max_length=255,
            ),
        ),
    ]
